apiVersion: storage.cnrm.cloud.google.com/v1beta1
kind: StorageBucket
metadata: # kpt-merge: /example
  annotations:
    cnrm.cloud.google.com/force-destroy: "false"
    cnrm.cloud.google.com/blueprint: 'kpt-pkg-fn'
  name: example # kpt-set: ${bucket-name}
spec:
  location: example # kpt-set: ${bucket-location}
